
import React, { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQAccordionItem: React.FC<{ item: FAQItem; isOpen: boolean; onClick: () => void }> = ({ item, isOpen, onClick }) => {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="border border-slate-200  rounded-2xl overflow-hidden bg-white mb-4 transition-all duration-300 hover:border-mint-400/50 shadow-sm hover:shadow-md"
    >
      <button
        onClick={onClick}
        className="w-full py-6 px-8 flex items-center justify-between text-left focus:outline-none cursor-pointer group"
      >
        <span className={`text-lg font-semibold transition-colors duration-300 ${isOpen ? 'text-mint-600' : 'text-primary-500'}`}>
          {item.question}
        </span>
        <motion.div 
          animate={{ rotate: isOpen ? 180 : 0 }}
          className={`ml-4 transition-colors duration-300 ${isOpen ? 'text-mint-500' : 'text-slate-400'}`}
        >
          <ChevronDown className="w-6 h-6" />
        </motion.div>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
          >
            <div className="px-8 pb-6 text-slate-600 leading-relaxed border-t border-slate-50 pt-4">
              {item.answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export const FAQSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs: FAQItem[] = [
    {
      question: "What is Menumakchha?",
      answer: "Menumakchha is a comprehensive digital menu management platform designed specifically for the hospitality industry. We empower restaurants, cafes, and hotels to create, manage, and share digital menus via QR codes, streamlining operations and improving guest safety."
    },
    {
      question: "Do I need to download the Menumakchha app to view menus?",
      answer: "No, one of the best features of Menumakchha is its accessibility. Customers can simply scan a QR code using their smartphone's native camera app. The menu opens instantly in their web browser without any additional downloads required."
    },
    {
      question: "How do I view a restaurant's menu using Menumakchha?",
      answer: "It's easy! Just point your phone's camera at the Menumakchha QR code displayed on the table. A notification or link will appear on your screen—tap it to access the full digital menu immediately."
    },
    {
      question: "What are the benefits of using Menumakchha for restaurants?",
      answer: "Restaurants benefit from significantly reduced printing costs, the ability to update items and prices in real-time, faster table turnover, and enhanced hygiene by eliminating physical menus that can carry germs."
    },
    {
      question: "Does Menumakchha mean \"What's on the Menu\" in Nepali?",
      answer: "Yes! The name is derived from the Nepali phrase \"Menu ma k chha?\", which literally translates to \"What is on the menu?\". It reflects our local roots and our focus on food discovery."
    },
    {
      question: "Is Menumakchha eco-friendly?",
      answer: "Absolutely. We are committed to sustainability. By moving menus to a digital format, we help hospitality businesses eliminate massive amounts of paper waste generated by printing and re-printing physical menus every time a change is made."
    }
  ];

  return (
    <section className="py-24 px-6 md:px-12 lg:px-20 bg-white w-full">
      <div className="max-w-4xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16 space-y-4"
        >
          <h2 className="text-4xl md:text-5xl font-bold text-primary-500 tracking-tight">
            Frequently asked questions
          </h2>
          <p className="text-slate-500 text-lg uppercase tracking-widest font-medium">
            Questions related to Menumakchha
          </p>
          <div className="h-1 w-24 bg-mint-400 mx-auto rounded-full mt-6"></div>
        </motion.div>

        <div className="space-y-2">
          {faqs.map((faq, index) => (
            <FAQAccordionItem 
              key={index} 
              item={faq} 
              isOpen={openIndex === index} 
              onClick={() => setOpenIndex(openIndex === index ? null : index)}
            />
          ))}
        </div>
      </div>
    </section>
  );
};
